### ISSUE TITLE
Unable to query the API

### ISSUE THREAD

**Issue by nicholaide** [AMarti96/docker-flowable#1]
Hi, completely new to Flowable and its ecosystem. 
I am getting a 404 error when trying to load [http://localhost:8080/flowable-rest/service/management/engine](http://localhost:8080/flowable-rest/service/management/engine. )

I tried `docker-compose up` and `docker-compose down` several times.
The error that seems to break the setup is:
```
flowit      | 09:36:46,709 [C3P0PooledConnectionPoolManager[identityToken->1bqrg1v9wimylulk05l4w|32ebdaec]-HelperThread-#2] WARN  com.mchange.v2.resourcepool.BasicResourcePool  - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@2de80590 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
flowit      | java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
```

**Comment by AMarti96** [comment]
Hello,

I do not know if it is still an issue, but the problem is not with the flowable environment but the sql one, since mysql 8 the default authentication is done via "caching_sha2_password" instead of "mysql_native_password", as it can be seen in [this link](https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/)

As the docker-compose is considering the latest image from mysql, it is using the new authentication method, try to use a previous mysql image:

```
mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-tier
```

If you want to use the newest mysql image, maybe you can take a look at [this page](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html) in order to use properly the new authentication method.

Hope it may help.
